### ISSUE TITLE
This template should create a default test directory

### ISSUE THREAD

**Issue by techyugadi** [sbt/sbt-fresh#143]
Should have a src/test directory created through the template

**Comment by hseeberger** [comment]
Empty directories are at odds with git, i.e. an empty directory won‘t be added to the initial commit (an optional feature of this plugin, defaulting to „on“).

**Comment by veera83372** [comment]
Generally, people tend to use `.keep` files in the empty directory to tracked by `git`

**Comment by hseeberger** [comment]
I think I don't want sbt-fresh to add src/test, because then pepole start asking for src/test/scala, src/test/java, etc. sbt-fresh has already become too complex for my taste and I want to restrict more features to such ones which are really helping a lot which is not the case for this one in my opinion as everyone should be able to create one or more directories within seconds.
